# Generated by Django 5.2 on 2025-04-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0001_initial'),
        ('requestFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfeedback',
            name='requested_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bin.bin'),
        ),
    ]
