# Generated by Django 5.2 on 2025-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0005_remove_bin_schedule'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bins',
            field=models.ManyToManyField(blank=True, to='bin.bin'),
        ),
    ]
