# Generated by Django 5.2 on 2025-04-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('user', '0005_delete_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.areamodel'),
        ),
    ]
