# Generated by Django 5.2 on 2025-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('citizen', 'Citizen'), ('collector', 'Collector'), ('helper', 'Helper')], default='citizen', max_length=10),
        ),
    ]
