# Generated by Django 5.2 on 2025-04-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
