# Generated by Django 5.2 on 2025-05-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_where_to_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_to',
        ),
    ]
