# Generated by Django 5.2 on 2025-04-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_to',
        ),
    ]
