# Generated by Django 5.2 on 2025-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
