# Generated by Django 5.2 on 2025-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_vehicle_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Mini-Truck', 'Mini Truck'), ('Pickup', 'Pickup')], max_length=100),
        ),
    ]
