# Generated by Django 5.2 on 2025-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestFeedback', '0002_requestfeedback_requested_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
