# Generated by Django 5.2 on 2025-04-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestFeedback', '0003_alter_requestfeedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='request_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('collection_request', 'Collection Request'), ('bin', 'Bin'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('other', 'Other')], default='feedback', max_length=20),
        ),
    ]
