# Generated by Django 5.2 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestFeedback', '0004_alter_requestfeedback_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
